// © mllbll 2025.
// Татарников Иван

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mllbll/space-manufacture/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, req
func (_m *InventoryService) GetPart(ctx context.Context, req model.GetPartRequest) (model.GetPartResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.GetPartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartRequest) (model.GetPartResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartRequest) model.GetPartResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.GetPartResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetPartRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.GetPartRequest
func (_e *InventoryService_Expecter) GetPart(ctx interface{}, req interface{}) *InventoryService_GetPart_Call {
	return &InventoryService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, req)}
}

func (_c *InventoryService_GetPart_Call) Run(run func(ctx context.Context, req model.GetPartRequest)) *InventoryService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GetPartRequest))
	})
	return _c
}

func (_c *InventoryService_GetPart_Call) Return(_a0 model.GetPartResponse, _a1 error) *InventoryService_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_GetPart_Call) RunAndReturn(run func(context.Context, model.GetPartRequest) (model.GetPartResponse, error)) *InventoryService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, req
func (_m *InventoryService) ListParts(ctx context.Context, req model.ListPartsRequest) (model.ListPartsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 model.ListPartsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsRequest) (model.ListPartsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsRequest) model.ListPartsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.ListPartsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListPartsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.ListPartsRequest
func (_e *InventoryService_Expecter) ListParts(ctx interface{}, req interface{}) *InventoryService_ListParts_Call {
	return &InventoryService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, req)}
}

func (_c *InventoryService_ListParts_Call) Run(run func(ctx context.Context, req model.ListPartsRequest)) *InventoryService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ListPartsRequest))
	})
	return _c
}

func (_c *InventoryService_ListParts_Call) Return(_a0 model.ListPartsResponse, _a1 error) *InventoryService_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_ListParts_Call) RunAndReturn(run func(context.Context, model.ListPartsRequest) (model.ListPartsResponse, error)) *InventoryService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
