// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package payment_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum структура для описания вариантов оплаты
type PaymentMethodEnum int32

const (
	PaymentMethodEnum_PAYMENT_METHOD_ENUM_UNSPECIFIED    PaymentMethodEnum = 0
	PaymentMethodEnum_PAYMENT_METHOD_ENUM_CARD           PaymentMethodEnum = 1
	PaymentMethodEnum_PAYMENT_METHOD_ENUM_SBP            PaymentMethodEnum = 2
	PaymentMethodEnum_PAYMENT_METHOD_ENUM_CREDIT_CARD    PaymentMethodEnum = 3
	PaymentMethodEnum_PAYMENT_METHOD_ENUM_INVESTOR_MONEY PaymentMethodEnum = 4
)

// Enum value maps for PaymentMethodEnum.
var (
	PaymentMethodEnum_name = map[int32]string{
		0: "PAYMENT_METHOD_ENUM_UNSPECIFIED",
		1: "PAYMENT_METHOD_ENUM_CARD",
		2: "PAYMENT_METHOD_ENUM_SBP",
		3: "PAYMENT_METHOD_ENUM_CREDIT_CARD",
		4: "PAYMENT_METHOD_ENUM_INVESTOR_MONEY",
	}
	PaymentMethodEnum_value = map[string]int32{
		"PAYMENT_METHOD_ENUM_UNSPECIFIED":    0,
		"PAYMENT_METHOD_ENUM_CARD":           1,
		"PAYMENT_METHOD_ENUM_SBP":            2,
		"PAYMENT_METHOD_ENUM_CREDIT_CARD":    3,
		"PAYMENT_METHOD_ENUM_INVESTOR_MONEY": 4,
	}
)

func (x PaymentMethodEnum) Enum() *PaymentMethodEnum {
	p := new(PaymentMethodEnum)
	*p = x
	return p
}

func (x PaymentMethodEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodEnum) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentMethodEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodEnum.Descriptor instead.
func (PaymentMethodEnum) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

// запрос который приходит от OrderService
type PayOrderMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PaymentMethod PaymentMethodEnum      `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.v1.PaymentMethodEnum" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderMessage) Reset() {
	*x = PayOrderMessage{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderMessage) ProtoMessage() {}

func (x *PayOrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderMessage.ProtoReflect.Descriptor instead.
func (*PayOrderMessage) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PayOrderMessage) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PayOrderMessage) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *PayOrderMessage) GetPaymentMethod() PaymentMethodEnum {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethodEnum_PAYMENT_METHOD_ENUM_UNSPECIFIED
}

// Responce для OrderService
type PayOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PayOrderResponse) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// обертка ответа от PaymentService
type PayOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PayOrderMessage *PayOrderMessage       `protobuf:"bytes,1,opt,name=pay_order_message,json=payOrderMessage,proto3" json:"pay_order_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayOrderRequest) GetPayOrderMessage() *PayOrderMessage {
	if x != nil {
		return x.PayOrderMessage
	}
	return nil
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\x93\x01\n" +
	"\x0fPayOrderMessage\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12D\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2\x1d.payment.v1.PaymentMethodEnumR\rpaymentMethod\"=\n" +
	"\x10PayOrderResponse\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\"Z\n" +
	"\x0fPayOrderRequest\x12G\n" +
	"\x11pay_order_message\x18\x01 \x01(\v2\x1b.payment.v1.PayOrderMessageR\x0fpayOrderMessage*\xc0\x01\n" +
	"\x11PaymentMethodEnum\x12#\n" +
	"\x1fPAYMENT_METHOD_ENUM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PAYMENT_METHOD_ENUM_CARD\x10\x01\x12\x1b\n" +
	"\x17PAYMENT_METHOD_ENUM_SBP\x10\x02\x12#\n" +
	"\x1fPAYMENT_METHOD_ENUM_CREDIT_CARD\x10\x03\x12&\n" +
	"\"PAYMENT_METHOD_ENUM_INVESTOR_MONEY\x10\x042W\n" +
	"\x0ePaymentService\x12E\n" +
	"\bPayOrder\x12\x1b.payment.v1.PayOrderRequest\x1a\x1c.payment.v1.PayOrderResponseBLZJgithub.com/mllbll/space_manufacture/shared/pkg/proto/payment/v1;payment_v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payment_v1_payment_proto_goTypes = []any{
	(PaymentMethodEnum)(0),   // 0: payment.v1.PaymentMethodEnum
	(*PayOrderMessage)(nil),  // 1: payment.v1.PayOrderMessage
	(*PayOrderResponse)(nil), // 2: payment.v1.PayOrderResponse
	(*PayOrderRequest)(nil),  // 3: payment.v1.PayOrderRequest
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PayOrderMessage.payment_method:type_name -> payment.v1.PaymentMethodEnum
	1, // 1: payment.v1.PayOrderRequest.pay_order_message:type_name -> payment.v1.PayOrderMessage
	3, // 2: payment.v1.PaymentService.PayOrder:input_type -> payment.v1.PayOrderRequest
	2, // 3: payment.v1.PaymentService.PayOrder:output_type -> payment.v1.PayOrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
