// © mllbll 2025.
// Татарников Иван

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mllbll/space-manufacture/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, param
func (_m *OrderRepository) Cancel(ctx context.Context, param string) (model.Order, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - param string
func (_e *OrderRepository_Expecter) Cancel(ctx interface{}, param interface{}) *OrderRepository_Cancel_Call {
	return &OrderRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, param)}
}

func (_c *OrderRepository_Cancel_Call) Run(run func(ctx context.Context, param string)) *OrderRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_Cancel_Call) Return(_a0 model.Order, _a1 error) *OrderRepository_Cancel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Cancel_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *OrderRepository) Create(ctx context.Context, req model.Order) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.Order
func (_e *OrderRepository_Expecter) Create(ctx interface{}, req interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, req model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(_a0 error) *OrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(context.Context, model.Order) error) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, params
func (_m *OrderRepository) Get(ctx context.Context, params string) (model.GetOrderResponce, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.GetOrderResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.GetOrderResponce, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.GetOrderResponce); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(model.GetOrderResponce)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - params string
func (_e *OrderRepository_Expecter) Get(ctx interface{}, params interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, params)}
}

func (_c *OrderRepository_Get_Call) Run(run func(ctx context.Context, params string)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(_a0 model.GetOrderResponce, _a1 error) *OrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.GetOrderResponce, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, param, req, transactionUUID
func (_m *OrderRepository) Pay(ctx context.Context, param string, req model.PayOrderRequest, transactionUUID string) error {
	ret := _m.Called(ctx, param, req, transactionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PayOrderRequest, string) error); ok {
		r0 = rf(ctx, param, req, transactionUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderRepository_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - param string
//   - req model.PayOrderRequest
//   - transactionUUID string
func (_e *OrderRepository_Expecter) Pay(ctx interface{}, param interface{}, req interface{}, transactionUUID interface{}) *OrderRepository_Pay_Call {
	return &OrderRepository_Pay_Call{Call: _e.mock.On("Pay", ctx, param, req, transactionUUID)}
}

func (_c *OrderRepository_Pay_Call) Run(run func(ctx context.Context, param string, req model.PayOrderRequest, transactionUUID string)) *OrderRepository_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PayOrderRequest), args[3].(string))
	})
	return _c
}

func (_c *OrderRepository_Pay_Call) Return(_a0 error) *OrderRepository_Pay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Pay_Call) RunAndReturn(run func(context.Context, string, model.PayOrderRequest, string) error) *OrderRepository_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
