// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
	//
	// Get order data by uuid.
	//
	// GET /api/v1/orders/{order_uuid}
	APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (APIV1OrdersOrderUUIDGetRes, error)
	// AddNewOrder implements AddNewOrder operation.
	//
	// Add new order.
	//
	// POST /api/v1/orders
	AddNewOrder(ctx context.Context, req *CreateOrderRequest) (AddNewOrderRes, error)
	// CancelOrder implements CancelOrder operation.
	//
	// Cancel Order.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Pay for order.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
