// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"io"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) aPIV1OrdersOrderUUIDGetRes() {}
func (*BadRequestError) addNewOrderRes()             {}
func (*BadRequestError) payOrderRes()                {}

type CancelOrderConflict struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s CancelOrderConflict) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*CancelOrderConflict) cancelOrderRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// Уникальный идентификатор заказа (UUID).
	UserUUID string `json:"user_uuid"`
	// Список UUID деталей.
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// Уникальный идентификатор заказа (UUID).
	OrderUUID OptString `json:"order_uuid"`
	// Итоговая стоимость.
	TotalPrice OptFloat32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() OptString {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() OptFloat32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val OptString) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val OptFloat32) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) addNewOrderRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

func (*GenericErrorStatusCode) aPIV1OrdersOrderUUIDGetRes() {}
func (*GenericErrorStatusCode) addNewOrderRes()             {}
func (*GenericErrorStatusCode) payOrderRes()                {}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	// Уникальный идентификатор заказа (UUID).
	OrderUUID string `json:"order_uuid"`
	// UUID пользователя.
	UserUUID string `json:"user_uuid"`
	// Список UUID деталей.
	PartUuids []string `json:"part_uuids"`
	// Итоговая стоимость.
	TotalPrice float32 `json:"total_price"`
	// Uuid транзакции (если оплачен).
	TransactionUUID string `json:"transaction_uuid"`
	// Способ оплаты:
	// 0 – Неизвестный
	// 1 – Банковская карта
	// 2 – СБП
	// 3 – Кредитная карта
	// 4 – Деньги инвестора.
	PaymentMethod OptGetOrderResponsePaymentMethod `json:"payment_method"`
	// Статус оплаты.
	Status GetOrderResponseStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() OptGetOrderResponsePaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() GetOrderResponseStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val OptGetOrderResponsePaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val GetOrderResponseStatus) {
	s.Status = val
}

func (*GetOrderResponse) aPIV1OrdersOrderUUIDGetRes() {}

// Способ оплаты:
// 0 – Неизвестный
// 1 – Банковская карта
// 2 – СБП
// 3 – Кредитная карта
// 4 – Деньги инвестора.
type GetOrderResponsePaymentMethod int

const (
	GetOrderResponsePaymentMethod0 GetOrderResponsePaymentMethod = 0
	GetOrderResponsePaymentMethod1 GetOrderResponsePaymentMethod = 1
	GetOrderResponsePaymentMethod2 GetOrderResponsePaymentMethod = 2
	GetOrderResponsePaymentMethod3 GetOrderResponsePaymentMethod = 3
	GetOrderResponsePaymentMethod4 GetOrderResponsePaymentMethod = 4
)

// AllValues returns all GetOrderResponsePaymentMethod values.
func (GetOrderResponsePaymentMethod) AllValues() []GetOrderResponsePaymentMethod {
	return []GetOrderResponsePaymentMethod{
		GetOrderResponsePaymentMethod0,
		GetOrderResponsePaymentMethod1,
		GetOrderResponsePaymentMethod2,
		GetOrderResponsePaymentMethod3,
		GetOrderResponsePaymentMethod4,
	}
}

// Статус оплаты.
type GetOrderResponseStatus string

const (
	GetOrderResponseStatusPENDINGPAYMENT GetOrderResponseStatus = "PENDING_PAYMENT"
	GetOrderResponseStatusPAID           GetOrderResponseStatus = "PAID"
	GetOrderResponseStatusCANCELLED      GetOrderResponseStatus = "CANCELLED"
)

// AllValues returns all GetOrderResponseStatus values.
func (GetOrderResponseStatus) AllValues() []GetOrderResponseStatus {
	return []GetOrderResponseStatus{
		GetOrderResponseStatusPENDINGPAYMENT,
		GetOrderResponseStatusPAID,
		GetOrderResponseStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetOrderResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case GetOrderResponseStatusPENDINGPAYMENT:
		return []byte(s), nil
	case GetOrderResponseStatusPAID:
		return []byte(s), nil
	case GetOrderResponseStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetOrderResponseStatus) UnmarshalText(data []byte) error {
	switch GetOrderResponseStatus(data) {
	case GetOrderResponseStatusPENDINGPAYMENT:
		*s = GetOrderResponseStatusPENDINGPAYMENT
		return nil
	case GetOrderResponseStatusPAID:
		*s = GetOrderResponseStatusPAID
		return nil
	case GetOrderResponseStatusCANCELLED:
		*s = GetOrderResponseStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) aPIV1OrdersOrderUUIDGetRes() {}
func (*InternalServerError) addNewOrderRes()             {}
func (*InternalServerError) payOrderRes()                {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) aPIV1OrdersOrderUUIDGetRes() {}
func (*NotFoundError) addNewOrderRes()             {}
func (*NotFoundError) cancelOrderRes()             {}
func (*NotFoundError) payOrderRes()                {}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGetOrderResponsePaymentMethod returns new OptGetOrderResponsePaymentMethod with value set to v.
func NewOptGetOrderResponsePaymentMethod(v GetOrderResponsePaymentMethod) OptGetOrderResponsePaymentMethod {
	return OptGetOrderResponsePaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptGetOrderResponsePaymentMethod is optional GetOrderResponsePaymentMethod.
type OptGetOrderResponsePaymentMethod struct {
	Value GetOrderResponsePaymentMethod
	Set   bool
}

// IsSet returns true if OptGetOrderResponsePaymentMethod was set.
func (o OptGetOrderResponsePaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetOrderResponsePaymentMethod) Reset() {
	var v GetOrderResponsePaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetOrderResponsePaymentMethod) SetTo(v GetOrderResponsePaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetOrderResponsePaymentMethod) Get() (v GetOrderResponsePaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetOrderResponsePaymentMethod) Or(d GetOrderResponsePaymentMethod) GetOrderResponsePaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPayOrderRequestPaymentMethod returns new OptPayOrderRequestPaymentMethod with value set to v.
func NewOptPayOrderRequestPaymentMethod(v PayOrderRequestPaymentMethod) OptPayOrderRequestPaymentMethod {
	return OptPayOrderRequestPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPayOrderRequestPaymentMethod is optional PayOrderRequestPaymentMethod.
type OptPayOrderRequestPaymentMethod struct {
	Value PayOrderRequestPaymentMethod
	Set   bool
}

// IsSet returns true if OptPayOrderRequestPaymentMethod was set.
func (o OptPayOrderRequestPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPayOrderRequestPaymentMethod) Reset() {
	var v PayOrderRequestPaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPayOrderRequestPaymentMethod) SetTo(v PayOrderRequestPaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPayOrderRequestPaymentMethod) Get() (v PayOrderRequestPaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPayOrderRequestPaymentMethod) Or(d PayOrderRequestPaymentMethod) PayOrderRequestPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	// Способ оплаты:
	// 0 – Неизвестный
	// 1 – Банковская карта
	// 2 – СБП
	// 3 – Кредитная карта
	// 4 – Деньги инвестора.
	PaymentMethod OptPayOrderRequestPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() OptPayOrderRequestPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val OptPayOrderRequestPaymentMethod) {
	s.PaymentMethod = val
}

// Способ оплаты:
// 0 – Неизвестный
// 1 – Банковская карта
// 2 – СБП
// 3 – Кредитная карта
// 4 – Деньги инвестора.
type PayOrderRequestPaymentMethod int

const (
	PayOrderRequestPaymentMethod0 PayOrderRequestPaymentMethod = 0
	PayOrderRequestPaymentMethod1 PayOrderRequestPaymentMethod = 1
	PayOrderRequestPaymentMethod2 PayOrderRequestPaymentMethod = 2
	PayOrderRequestPaymentMethod3 PayOrderRequestPaymentMethod = 3
	PayOrderRequestPaymentMethod4 PayOrderRequestPaymentMethod = 4
)

// AllValues returns all PayOrderRequestPaymentMethod values.
func (PayOrderRequestPaymentMethod) AllValues() []PayOrderRequestPaymentMethod {
	return []PayOrderRequestPaymentMethod{
		PayOrderRequestPaymentMethod0,
		PayOrderRequestPaymentMethod1,
		PayOrderRequestPaymentMethod2,
		PayOrderRequestPaymentMethod3,
		PayOrderRequestPaymentMethod4,
	}
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// Uuid транзакции (если оплачен).
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}
