// © mllbll 2025.
// Татарников Иван

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mllbll/space-manufacture/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, param
func (_m *OrderService) Cancel(ctx context.Context, param string) error {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - param string
func (_e *OrderService_Expecter) Cancel(ctx interface{}, param interface{}) *OrderService_Cancel_Call {
	return &OrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, param)}
}

func (_c *OrderService_Cancel_Call) Run(run func(ctx context.Context, param string)) *OrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_Cancel_Call) Return(_a0 error) *OrderService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *OrderService) Create(ctx context.Context, req model.CreateOrderRequest) (model.CreateOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (model.CreateOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) model.CreateOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.CreateOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateOrderRequest
func (_e *OrderService_Expecter) Create(ctx interface{}, req interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *OrderService_Create_Call) Run(run func(ctx context.Context, req model.CreateOrderRequest)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(_a0 model.CreateOrderResponse, _a1 error) *OrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(context.Context, model.CreateOrderRequest) (model.CreateOrderResponse, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, params
func (_m *OrderService) Get(ctx context.Context, params string) (model.GetOrderResponce, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.GetOrderResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.GetOrderResponce, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.GetOrderResponce); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(model.GetOrderResponce)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - params string
func (_e *OrderService_Expecter) Get(ctx interface{}, params interface{}) *OrderService_Get_Call {
	return &OrderService_Get_Call{Call: _e.mock.On("Get", ctx, params)}
}

func (_c *OrderService_Get_Call) Run(run func(ctx context.Context, params string)) *OrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_Get_Call) Return(_a0 model.GetOrderResponce, _a1 error) *OrderService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Get_Call) RunAndReturn(run func(context.Context, string) (model.GetOrderResponce, error)) *OrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, param, req
func (_m *OrderService) Pay(ctx context.Context, param string, req model.PayOrderRequest) (model.PayOrderResponse, error) {
	ret := _m.Called(ctx, param, req)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 model.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PayOrderRequest) (model.PayOrderResponse, error)); ok {
		return rf(ctx, param, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PayOrderRequest) model.PayOrderResponse); ok {
		r0 = rf(ctx, param, req)
	} else {
		r0 = ret.Get(0).(model.PayOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PayOrderRequest) error); ok {
		r1 = rf(ctx, param, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - param string
//   - req model.PayOrderRequest
func (_e *OrderService_Expecter) Pay(ctx interface{}, param interface{}, req interface{}) *OrderService_Pay_Call {
	return &OrderService_Pay_Call{Call: _e.mock.On("Pay", ctx, param, req)}
}

func (_c *OrderService_Pay_Call) Run(run func(ctx context.Context, param string, req model.PayOrderRequest)) *OrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PayOrderRequest))
	})
	return _c
}

func (_c *OrderService_Pay_Call) Return(_a0 model.PayOrderResponse, _a1 error) *OrderService_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Pay_Call) RunAndReturn(run func(context.Context, string, model.PayOrderRequest) (model.PayOrderResponse, error)) *OrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
