// Code generated by ogen, DO NOT EDIT.
package order_v1

type APIV1OrdersOrderUUIDGetRes interface {
	aPIV1OrdersOrderUUIDGetRes()
}

type AddNewOrderRes interface {
	addNewOrderRes()
}

type CancelOrderRes interface {
	cancelOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
