// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
//
// Get order data by uuid.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (r APIV1OrdersOrderUUIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddNewOrder implements AddNewOrder operation.
//
// Add new order.
//
// POST /api/v1/orders
func (UnimplementedHandler) AddNewOrder(ctx context.Context, req *CreateOrderRequest) (r AddNewOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelOrder implements CancelOrder operation.
//
// Cancel Order.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Pay for order.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}
